site_name: "Matchbox"
site_description: "Documentation for Matchbox"
repo_url: "https://github.com/uktrade/matchbox"
repo_name: "uktrade/matchbox"

nav:
- Home:
  - Welcome: index.md
  - Use cases: use-cases.md
- Client:
  - Installation: client/install.md
  - Explore resolutions: client/explore-resolutions.md
  - Retrieve: client/query-data.md
  - Link and deduplicate: client/link-data.md
  - Evaluate models: client/evaluation.md
  - API: 
    - Overview: api/client/index.md
- Server:
  - Matchbox concepts: server/concepts.md
  - Installation: server/install.md
  - Deploy: server/deploy.md
  - Data and security risks: server/risks.md
  - API: 
    - Overview: api/server/index.md
- API reference:
  - Client:
    - Overview: api/client/index.md
    - DAGs: api/client/dags.md
    - Evaluation: api/client/eval.md
    - Helpers: api/client/helpers.md
    - Models: api/client/models.md
    - Results: api/client/results.md
    - Visualisation: api/client/visualisation.md
    - Extract: api/client/extract.md
  - Server: 
    - Overview: api/server/index.md
    - API: api/server/api.md
    - Uploads: api/server/uploads.md
    - Backends:
      - PostgreSQL: api/server/backends/postgresql.md
  - Common: 
    - Overview: api/common/index.md
    - Database: api/common/db.md
    - Evaluation: api/common/eval.md
    - Exceptions: api/common/exceptions.md
    - Factories: 
      - Overview: api/common/factories/index.md
      - Entities: api/common/factories/entities.md
      - Sources: api/common/factories/sources.md
      - Models: api/common/factories/models.md
    - Graph: api/common/graph.md
    - Hashing: api/common/hash.md
    - Logging: api/common/logging.md
    - Transform: api/common/transform.md
    - Sources: api/common/sources.md
    - DTOs: api/common/dtos.md
    - Arrow: api/common/arrow.md
- Contributing:
  - Guidelines: contributing.md

theme:
  name: material
  logo: assets/matchbox-icon.svg
  favicon: assets/matchbox-icon-dark.png
  features:
    - content.code.copy
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - smarty
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.caption
  - toc:
      permalink: true

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          inventories:
          - https://docs.python.org/3/objects.inv
          - https://typing-extensions.readthedocs.io/en/latest/objects.inv
          paths: [src]
          options:
            extensions:
              - griffe_inherited_docstrings
            docstring_options:
              ignore_init_summary: true
            preload_modules: [matchbox]
            docstring_style: google
            docstring_section_style: list
            heading_level: 2
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            show_bases: true
            show_inheritance_diagram: true
            show_root_full_path: false
            show_source: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            extra:
              show_docstring_inheritance: true
              show_inheritance: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/uktrade/matchbox
  generator: false

extra_css:
  - stylesheets/extra.css
